'*.{tx,tsx,js}':
  - 'cd .. && eslint --cache --cache-location ./backend/node_modules/.cache/.eslintcache --ext .ts ./backend --fix'
  - 'prettier --loglevel warn --cache --write'
'*.{json,yml,sccs}': 'prettier --loglevel warn --cache --write'
